# https://leetcode.com/explore/challenge/card/september-leetcoding-challenge/557/week-4-september-22nd-september-28th/3471/
# https://leetcode.com/problems/find-the-difference/
#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more 
# letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#     Input:
#         s = "abcd"
#         t = "abcde"
#     Output:
#         e
#     Explanation:
#         'e' is the letter that was added.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        debug = False
        sHash = {}
        tHash = {}
        noDifference = ''
        for i in range(len(s)):
            if s[i] in sHash:
                sHash[s[i]] += 1
            else:
                sHash[s[i]] = 1
        if debug: print(sHash)
        for i in range(len(t)):
            if t[i] in tHash:
                tHash[t[i]] += 1
            else:
                tHash[t[i]] = 1
        if debug: print(tHash)
        for key in tHash:
            if key not in sHash:
                if debug: print("%s not found in tHash" % key)
                return key
            elif tHash[key] != sHash[key]:
                return key
        return noDifference

s = Solution()
sInput = "abcd"
tInput = "abcde"
solution = 'e'
output = s.findTheDifference(sInput,tInput)
print('%s | %s' % ('PASS' if output == solution else 'FAIL', output))